# Site Build Settings

# jekyll-paginate configuration
paginate:            50

# Build settings
markdown:            kramdown
exclude:             ["README.md"]
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
future:              true # Posts with future dates will be included

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Intercultural Communication & Religious Change"
description:	       "Intercultural Communication in Changing Religious Milieus: Comparative Investigations | Interkulturelle Kommunikationswege in sich wandelnden religiösen Umfeldern. Vergleichende Untersuchungen"
author:              "Nathan Gibson"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

hide_related_posts: true
hide_post_share: true